### PR TITLE
Update README.md - Adding Instagram OSINT tools

### PR DESCRIPTION
**Pull request by brunoooost**
Adding Instagram OSINT tools: 

- [Instaloctrack](https://github.com/bernsteining/instaloctrack) -> Tool for tracking Instagram locations.
- [Instagram Crawler](https://github.com/hehpollon/Instagram-Crawler)  Tool for scraping Instagram data.
- [InstaLooter](https://github.com/althonos/InstaLooter) - Tool for downloading photos and videos from Instagram profiles.

### CODE REVIEW

**Comment by spmedia** [comment]
ello,

Have you confirmed these scripts still actually work?

They have last been updated 3 to 4 years ago which is forever in tech.

instaloctrack is even archived by its owned and read only.

**Comment by chrisdave978** [comment]
For those people that are into Cryptocurrency know how frustrating it is to lose your Cryptocurrency to a fake online investment platform. When this happens, one needs the best recovery expert and I was lucky to have found one (hack4net8@gmail .com)

**Comment by brunoooost** [comment]
yes, instaloctrack is archived but they work

**Comment by spmedia** [comment]
> yes, instaloctrack is archived but they work

https://github.com/hehpollon/Instagram-Crawler

I just tested this one, it does not work.

Please only submit scripts you have personally used and know work.

Thnx

**Comment by brunoooost** [comment]
okey

**Comment by chrisdave978** [comment]
MY CRYPTO RECOVERY EXPERIENCE 2024 WARNING: Scammers will stop at nothing to steal your hard-earned money! But, I’m living proof that JETWEBHACKERS can help you RECLAIM YOUR LOST FUNDS! I thought I’d lost my life savings of $58,000 after investing with a fake broker, promising me a whopping $187,000 profit to fund my urgent surgery. But, JETWEBHACKERS didn’t give up on me. They worked tirelessly to track down my money and recover it. And, after months of intense effort, they successfully recovered my entire investment – $58,000! I’m now able to focus on my health and recovery, knowing that I’ve been given a second chance thanks to JETWEBHACKERS. Don’t let scammers ruin your life like they almost did mine! If you’re in a similar situation, don’t hesitate to reach out to JETWEBHACKERS. They’ll be your champion in the fight against online fraud!” CONTACT THEM VIA EMAIL:(hack4net8@gmail .com)

**Pull request closed without merging**
