### PR TITLE
Added BingeBooks to the Books and Reading List

### PR DESCRIPTION
**Pull request by clementeizurieta**
Added bingebooks.com to the Books and Reading list

### CODE REVIEW

**Comment by clementeizurieta** [comment]
Was there a reason this was not merged to master?  Thanks.

**Comment by spmedia** [comment]
> Was there a reason this was not merged to master? Thanks.

At a fast glance it seemed like it might have been self-promotional but I was mistaken. My apologies. Will merge in now.

**Comment by clementeizurieta** [comment]
thank you.

**Comment by spmedia** [comment]
> thank you.

Actually. It is self-promotional.

You are the "CTO Authors A.I." and the website is "© 2022 Authors A.I."

**Comment by clementeizurieta** [comment]
Thank you.  We are a very small company, however very much legitimate.  It is not my intention to self-promote, but rather just to add the link to this list.  I could ask a third party to request the addition however not many had the GitHub expertise.

**Pull request merged**
